version: '3'

tasks:
  setup:
    desc: Подготовка окружения
    cmds:
      - echo "🧰 Подготовка окружения..."
      - echo "📦 Обновляю зависимости Go (go mod tidy)..."
      - go mod tidy
      - cp .env.example .env
      - |
        echo -n "➡️ Введите Telegram токен: "
        read TOKEN
        sed -i.bak "s|^TELEGRAM_TOKEN=.*|TELEGRAM_TOKEN=$$TOKEN|" .env
        rm -f .env.bak
      - echo "✅ Готово. Можно запускать: task run"

  run:
    desc: Запуск тестов и Docker
    cmds:
      - echo "🧪 Запускаю тесты..."
      - go test ./...
      - echo "🐳 Запускаю Docker..."
      - docker compose up --build
