version: '3'

tasks:
  setup:
    desc: Подготовка окружения
    cmds:
      - echo "Подготовка окружения..."
      - go mod tidy
      - cp .env.example .env
      - echo "Готово. Укажите токен через 'task setup:token -- <ваш_токен>', затем 'task run'"

  setup:token:
    desc: Установить Telegram токен в .env
    cmds:
      - sed -i.bak "s|^TELEGRAM_TOKEN=.*|TELEGRAM_TOKEN={{.CLI_ARGS}}|" .env
      - rm -f .env.bak
      - echo "Токен установлен."
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Укажите токен: task setup:token -- <ваш_токен>"

  run:
    desc: Запуск тестов и Docker
    cmds:
      - echo "Запускаю тесты..."
      - go test ./...
      - echo "Запускаю Docker..."
      - docker compose up --build

  test:
    desc: Запуск тестов
    cmds:
      - go test ./...
